import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState } from "react";
import styles from "../styles/Home.module.css";



export default function Home() {
  const router = useRouter();
  const [name, setName] = useState("");
  const [id, setId] = useState("");
  const [id2, setId2] = useState("");
  const [id3, setId3] = useState("");
  const [msg, setMsg] = useState("");
  const handleSubmit = (e) => {

    e.preventDefault();
    if (id.length === 15 && id2.length === 7 && id3.length === 8) {
      router.push(`/upload?id=${id}&id2=${id2}&id3=${id3}&name=${name}`)
    } else {
      if (id.length !== 15) {
        setMsg("Emirates ID should be 15 digits")
      }
      if (id2.length !== 7) {
        setMsg("Driving License should be 7 digits")
      }
      if (id3.length !== 8) {
        setMsg("Passport Copy should be 8 digits")
      }



    }

  }



  return (
    <div className="flex items-center justify-center w-screen h-screen bg-white">
      <Head>
        <title>Emmirates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form>
        <div className="flex flex-col bg-gray-100 p-10 rounded-lg w-96">
          <input
            className="p-2 rounded-xl my-2 outline-none "
            type="text"
            placeholder="Name"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          <input
            className="p-2 rounded-xl my-2  outline-none "
            type="text"
            placeholder="Emmirate ID"
            value={id}
            style={{ border: id.length === 0 || id.length === 15 ? "" : "1px solid red" }}

            onChange={(e) =>

              setId(e.target.value)



            }
          />
          <input
            className="p-2 rounded-xl my-2  outline-none "
            type="text"
            placeholder="Driving License"
            value={id2}

            style={{ border: id2.length === 0 || id2.length === 7 ? "" : "1px solid red" }}
            onChange={(e) => setId2(e.target.value)}
          />
          <input
            className="p-2 rounded-xl my-2  outline-none "
            type="text"
            placeholder="Passport Number"
            value={id3}
            style={{ border: id3.length === 0 || id3.length === 8 ? "" : "1px solid red" }}
            onChange={(e) => setId3(e.target.value)}
          />
          <p className="text-red-500 text-center py-2">  {msg} </p>
          <button
            className=" bg-blue-500 rounded-2xl my-2 p-3 text-white"
            onClick={handleSubmit}
          >
            Submit
          </button>
        </div>
      </form>
    </div>
  );
}
