import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  const [name, setName] = useState("");
  const [id, setId] = useState("");
  const [id2, setId2] = useState("");
  const [id3, setId3] = useState("");
  const [id4, setId4] = useState("");
  const [id5, setId5] = useState("");
  const [id6, setId6] = useState("");
  // const [id7, setId7] = useState("");
  // const [id8, setId8] = useState("");
  // const [id9, setId9] = useState("");

  const [msg, setMsg] = useState("");
  const handleSubmit = (e) => {
    e.preventDefault();
    // if (
    //   id.length === 15 &&
    //   id2.length === 7 &&
    //   id3.length === 6 &&
    //   id4.length === 6 &&
    //   id5.length === 4 &&
    //   id6.length === 7 &&
    //   id7.length === 5 &&
    //   id9.length === 5
    // ) {
    router.push(
      `/upload?id=${id}&id2=${id2}&id3=${id3}&id4=${id4}&id5=${id5}&id6=${id6}&name=${name}`
    );
    //     );
    //   } else {
    //     if (id.length !== 15) {
    //       setMsg("Emirates ID should be 15 digits");
    //     }
    //     if (id2.length !== 7) {
    //       setMsg("Driving License should be 7 digits");
    //     }
    //     if (id3.length !== 6) {
    //       setMsg("dubai Copy should be 8 digits");
    //     }

    //     if (id4.length !== 6) {
    //       setMsg("sharjah Copy should be 6 digits");
    //     }
    //     if (id5.length !== 4) {
    //       setMsg("umm al quwain Copy should be 6 digits");
    //     }
    //     if (id6.length !== 7) {
    //       setMsg("abu dhabi Copy should be 6 digits");
    //     }
    //     if (id7.length !== 5) {
    //       setMsg("Ajman Copy should be 6 digits");
    //     }
    //     if (id8.length !== 5) {
    //       setMsg("Passport Copy should be 6 digits");
    //     }
    //     // if (id9.length !== 5) {
    //     //   setMsg("RAS Copy should be 6 digits");
    //     // }
    //   }
  };

  return (
    <div className="flex items-center justify-center w-screen h-screen bg-white">
      <Head>
        <title>Emmirates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form>
        <div className="flex flex-col bg-gray-100 p-10 rounded-lg w-96">
          <input
            className="p-2 rounded-xl my-2 outline-none "
            type="text"
            placeholder="Name"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />

          <input
            className="p-2 rounded-xl my-2  outline-none "
            type="text"
            placeholder="License No. (Abu dhabi)"
            value={id}
            style={{
              border: id.length === 0 || id.length === 6 ? "" : "1px solid red",
            }}
            onChange={(e) => setId(e.target.value)}
          />

          <input
            className="p-2 rounded-xl my-2  outline-none "
            type="text"
            placeholder="License No. (Sharjah)"
            value={id2}
            style={{
              border:
                id2.length === 0 || id2.length === 6 ? "" : "1px solid red",
            }}
            onChange={(e) => setId2(e.target.value)}
          />

          <input
            className="p-2 rounded-xl my-2  outline-none "
            type="text"
            placeholder="License No.(Umm Al-Quwain) "
            value={id3}
            style={{
              border:
                id3.length === 0 || id3.length === 4 ? "" : "1px solid red",
            }}
            onChange={(e) => setId3(e.target.value)}
          />

          <input
            className="p-2 rounded-xl my-2  outline-none "
            type="text"
            placeholder="License No. (Dubai)"
            value={id4}
            style={{
              border:
                id4.length === 0 || id4.length === 7 ? "" : "1px solid red",
            }}
            onChange={(e) => setId4(e.target.value)}
          />

          <input
            className="p-2 rounded-xl my-2  outline-none "
            type="text"
            placeholder="License No. (Ajman)"
            value={id5}
            style={{
              border:
                id5.length === 0 || id5.length === 5 ? "" : "1px solid red",
            }}
            onChange={(e) => setId5(e.target.value)}
          />

          {/* <input
            className="p-2 rounded-xl my-2  outline-none "
            type="text"
            placeholder="License No. (Fujairah)"
            value={id8}
            style={{
              border:
                id8.length === 0 || id8.length === 6 ? "" : "1px solid red",
            }}
            onChange={(e) => setId8(e.target.value)}
          /> */}

          <input
            className="p-2 rounded-xl my-2  outline-none "
            type="text"
            placeholder="License No.(Ras al Khaimah)"
            value={id6}
            style={{
              border:
                id6.length === 0 || id6.length === 5 ? "" : "1px solid red",
            }}
            onChange={(e) => setId6(e.target.value)}
          />

          <input
            className="p-2 rounded-xl my-2  outline-none "
            type="text"
            placeholder="Emmirate ID"
          // value={id7}
          // style={{
          //   border:
          //     id7.length === 0 || id7.length === 15 ? "" : "1px solid red",
          // }}
          // onChange={(e) => setId7(e.target.value)}
          />
          <input
            className="p-2 rounded-xl my-2  outline-none "
            type="text"
            placeholder="Passport UID"
          // value={id8}
          // style={{
          //   border:
          //     id8.length === 0 || id8.length === 7 ? "" : "1px solid red",
          // }}
          // onChange={(e) => setId8(e.target.value)}
          />

          <p className="text-red-500 text-center py-2"> {msg} </p>
          <button
            className=" bg-blue-500 rounded-2xl my-2 p-3 text-white"
            onClick={handleSubmit}
          >
            Submit
          </button>
        </div>
      </form>
    </div>
  );
}